name: GWTime Closing Time

on:
  schedule:
    - cron: "29,34,39 * * * 1-5"
      timezone: "America/Chicago"
  workflow_dispatch:

jobs:
  closing-time:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GWTime closing time
        run: |
          curl --fail-with-body -sS "${{ secrets.GWTIME_CLOSING_URL }}"
