name: GWTime Closing Time

on:
  schedule:
    - cron: "29,34,39,44,49,54,59 20,21 * * 1-5"
  workflow_dispatch:

  workflow_dispatch:

jobs:
  closing-time:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger GWTime closing time
        run: |
          curl --fail-with-body "${{ secrets.GWTIME_CLOSING_URL }}"
